### ISSUE TITLE
Re-train model without shadow mask

### ISSUE THREAD

**Issue by hnrna** [GuoLanqing/ShadowFormer#13]
> You can use an existing shadow detector to pre-predicted a shadow mask, then input it into the ShadowFormer.
> Or you can re-train the model without the shadow mask.
> 
> _Originally posted by @GuoLanqing in https://github.com/GuoLanqing/ShadowFormer/issues/7#issuecomment-1445648681_

Hello, have you experimented with retraining the model without the shadow mask?
If you have tried, is the model trained in the above way still able to achieve the effect of de-shadowing? And how do the evaluation metrics perform?

**Comment by wmj183363206** [comment]
No, I still use the dataset with shadow mark. There is a 'xm' in forward function, which I think is the required shadow mask.

**Comment by GuoLanqing** [comment]
You can use a pre-trained shadow detector if there is no GT shadow mask. Alternatively, you can train without the shadow mask, but you need to remove the SIA module.

**Comment by hnrna** [comment]
Thank you for your suggestion, I will try to modify the model.
