### ISSUE TITLE
Why are the weights so big? ISTD_model_latest.pth (131M) 

### ISSUE THREAD

**Issue by igodogi** [GuoLanqing/ShadowFormer#14]
According to the paper table, the parameters number of ShadowFormer is only 2.4M.  Why is the weight file provided so large?

**Comment by GuoLanqing** [comment]
ShadowFormer has two versions. I only released the large one first. And the released version would be slightly larger than the Ours-Large, but the performance would also be better than the results reported in the paper.

I will release the whole version as soon as possible. Thanks for your interest.

**Comment by GuoLanqing** [comment]
The released version has around 11M parameters.

**Comment by igodogi** [comment]
Still confused. If saved as FP32 format, the weights may be 11M*4=44MB. Why 131MB?

**Comment by GuoLanqing** [comment]
You can try to calculate the number of model_restoration.parameters().
________________________________
发件人: igodogi ***@***.***>
发送时间: 2023年3月13日 16:19
收件人: GuoLanqing/ShadowFormer ***@***.***>
抄送: #GUO LANQING# ***@***.***>; Comment ***@***.***>
主题: Re: [GuoLanqing/ShadowFormer] Why are the weights so big? ISTD_model_latest.pth (131M) (Issue #14)


Still confused. If saved as FP32 format, the weights may be 11M*4=44MB. Why 131MB?

―

**Comment by igodogi** [comment]
OK. I find your *.pth inculding the 'optimizer', so it is two times bigger. Actually it is 44MB just for weights.
