### ISSUE TITLE
RuntimeError after five epoch

### ISSUE THREAD

**Issue by Meow-2** [GuoLanqing/ShadowFormer#15]
dataset: AISTD
command: `python train.py --warmup --win_size 8 --train_ps 256`
```
File "/home/zk/Code/Python/ShadowFormer/model.py", line 546, in window_partition
    x = x.view(B, H // win_size, win_size, W // win_size, win_size, C)
RuntimeError: shape '[1, 7, 8, 10, 8, 256]' is invalid for input of size 1228800
```
How can I fix it?

**Comment by GuoLanqing** [comment]
What's your training image size? 256*256 or original size?

**Comment by Meow-2** [comment]
> What's your training image size? 256*256 or original size?

original size, 640*480

**Comment by GuoLanqing** [comment]
For that size, I recommend using the `--win_size 10 --train_ps 320` or `--win_size 10 --train_ps 240`. If `train_ps` is larger, the performance would be better.

**Comment by Meow-2** [comment]
Thank you, it works well now.

**Comment by jck666666** [comment]
@Meow-2 
May I ask how you set the arguments for testing with the command python train.py --warmup --win_size 8 --train_ps 256? Did you also use the --tile argument in test.py?
