### ISSUE TITLE
SRD dataset natively lacking shadow mask, how to do training and inference?

### ISSUE THREAD

**Issue by hnrna** [GuoLanqing/ShadowFormer#17]
Hi, your work seems to have strong and effective!

But I have some confusion about using the SRD dataset, how do you use the SRD dataset for training and inference since the SRD dataset natively lacks shadow mask?

Or is there some way to get the shadow mask of each image pair by shadow image and no-shadow image pairs?
(e.g. directly find the difference of image pairs and binarize it to shadow mask with certain threshold)

**Comment by xuhangc** [comment]
SRD masks can be found in DHAN repo [SRD Mask](https://uofmacau-my.sharepoint.com/:u:/g/personal/yb87432_umac_mo/EZ8CiIhNADlAkA4Fhim_QzgBfDeI7qdUrt6wv2EVxZSc2w?e=hobVMfurl)
