### ISSUE TITLE
About shadow detection.

### ISSUE THREAD

**Issue by igodogi** [GuoLanqing/ShadowFormer#2]
Hi， thanks for your great work. I can't wait for your code release.

But, after reading the paper,  I am wondering where is the  **I_m** from. 
Did you use the dataset's mask directly? 
If so, which **model** do you think should be used for **I_m** detection in the deploy environment?
![image](https://user-images.githubusercontent.com/26406574/219684450-c091e0a7-c3b4-4e04-9f6b-eba9c7a9dd61.png)

**Comment by GuoLanqing** [comment]
Thanks for your interest. The code will be released very soon. 
In our experiments, we followed the same settings as most previous methods: the shadow mask in the ISTD dataset is provided in their dataset, and the shadow mask for the SRD dataset is detected by DHAN (AAAI20).
