### ISSUE TITLE
inference on noisy images without masks 

### ISSUE THREAD

**Issue by tardigrade-10** [GuoLanqing/ShadowFormer#21]
Hi, I am trying to predict clean images from noisy images directly without using masks, ultimately a predict.py file that take the input images only. how can this be done? and are you planning to work on it?

**Comment by GuoLanqing** [comment]
Thanks for your interest. You can use an external pre-trained shadow detector to generate the shadow mask. Or you can also re-train the shadow removal model and fix the shadow mask as the all-one matrix.
We will try to include the mask-free version in our repo in the future.

**Comment by CrazyBrick** [comment]
> Thanks for your interest. You can use an external pre-trained shadow detector to generate the shadow mask. Or you can also re-train the shadow removal model and fix the shadow mask as the all-one matrix. We will try to include the mask-free version in our repo in the future.

@GuoLanqing hi, have you provided this version ? or just I missed it?
