### ISSUE TITLE
 I am unable to reach your PSNR.

### ISSUE THREAD

**Issue by Hedlen** [GuoLanqing/ShadowFormer#22]
Hi,
    I follow your provided code and keep your setting. However, I am unable to reach your PSNR. Could you please provide me with the training code and pre-train model that can reach this number? Thank you very much !
<img width="653" alt="image" src="https://user-images.githubusercontent.com/23314153/236436667-55ff368f-5a9c-403d-b803-0592eadbc385.png">

**Comment by GuoLanqing** [comment]
Thanks for your interest. Our released pre-trained model can reach the reported results in the paper. As we mentioned in the experiment part, following previous works, our evaluation includes two settings, i.e., evaluated in 256*256 and the original resolution. If you want to reach the results of 256 *256, you should resize the results first and then calculate the PSNR and SSIM.
