### ISSUE TITLE
About the pretrained model

### ISSUE THREAD

**Issue by WUyinwei-hah** [GuoLanqing/ShadowFormer#3]
Hi, thank you for your great work!
 But I found I can't download the pretrained model with the link provided in the project, which directed me to a 404 page. 
![image](https://user-images.githubusercontent.com/56622077/219991131-2f434bed-4a02-4747-b56a-c2d7954d03da.png)

**Comment by GuoLanqing** [comment]
Thanks for your interest. The pretrained model will be released soon after checking the reproducibility.

**Comment by GuoLanqing** [comment]
You can also train the model by yourself using the existing version.

**Comment by WUyinwei-hah** [comment]
Got it, thank you!
