### ISSUE TITLE
Testing with custom data

### ISSUE THREAD

**Issue by Alive59** [GuoLanqing/ShadowFormer#5]
Is it possible for testing using data without ground truth (test_B, test_C folders) ?

**Comment by GuoLanqing** [comment]
You can use any existing shadow detector, e.g., DHAN (AAAI2020), to predict the shadow mask. Then input the testing image and corresponding predicted shadow mask into the network for testing. The `test_C` folder is GT, which is not compulsory if you do not want to calculate the metrics.

**Comment by Alive59** [comment]
> You can use any existing shadow detector, e.g., DHAN (AAAI2020), to predict the shadow mask. Then input the testing image and corresponding predicted shadow mask into the network for testing. The `test_C` folder is GT, which is not compulsory if you do not want to calculate the metrics.

Okay I see. Thanks for the quick reply!
