### ISSUE TITLE
no result in folder

### ISSUE THREAD

**Issue by fariou73** [GuoLanqing/ShadowFormer#6]
Hello. Problem with run this
![image](https://user-images.githubusercontent.com/13123303/221335071-e3df223d-eafe-4d4d-b5de-2136ccd5da26.png)

**Comment by GuoLanqing** [comment]
It seems that your folder has no images. Can you show me the structure of your `input_dir`?

**Comment by fariou73** [comment]
the problem was with the png extension.
![image](https://user-images.githubusercontent.com/13123303/221355638-7226eb8c-ebcc-4acc-9956-984189867c7d.png)
