### ISSUE TITLE
Question about the used dataset

### ISSUE THREAD

**Issue by wmj183363206** [GuoLanqing/ShadowFormer#7]
Can the ShadowFormer process the dataset without gt_mask ?

**Comment by GuoLanqing** [comment]
You can use an existing shadow detector to pre-predicted a shadow mask, then input it into the ShadowFormer.
Or you can re-train the model without the shadow mask.

**Comment by wmj183363206** [comment]
OK. Thank you for your reply.

**Comment by wmj183363206** [comment]
你好，我想问一下如果我是用宽度为960高度为720的图片，这个训练指令可以是这样的吗？
python train.py --warmup --win_size 12 --train_ps 720

**Comment by hnrna** [comment]
> You can use an existing shadow detector to pre-predicted a shadow mask, then input it into the ShadowFormer. Or you can re-train the model without the shadow mask.

Have you experimented with re-training the model without the shadow mask?
Can the model trained in the above way still achieve the effect of de-shadowing? And how do the evaluation metrics perform?

**Comment by GuoLanqing** [comment]
The `train_ps` should be a multiple of the `win_size` * 8. Thus you can train with the `win_size`=10. Alternatively, the `train_ps`=720 is very large, leading to a large GPU memory. You can choose a smaller `train_ps`.

**Comment by wmj183363206** [comment]
Thank you for your patient reply. ^ . ^

**Comment by hnrna** [comment]
> The `train_ps` should be a multiple of the `win_size` * 8. Thus you can train with the `win_size`=10. Alternatively, the `train_ps`=720 is very large, leading to a large GPU memory. You can choose a smaller `train_ps`.

Have you experimented with the effect of adjusting the parameters `--win_size` and `--train_ps` on the effect of the model?

In addition does the program limit the upper limit of the parameters `--win_size` and `--train_ps`?
