### ISSUE TITLE
About the license for this model

### ISSUE THREAD

**Issue by PINTO0309** [GuoLanqing/ShadowFormer#8]
Thank you for sharing your great code. :smiley_cat:

What is the license for this model? I'd like to cite it to the repository I'm working on if possible, but I want to post the license correctly.
https://github.com/PINTO0309/PINTO_model_zoo
https://github.com/PINTO0309/onnx2tf

Btw, I have already successfully converted to ONNX, TensorFlow and TensorFlow Lite.
Thank you.

**Comment by GuoLanqing** [comment]
I have updated the LICENSE in the repo. Thanks~

**Comment by PINTO0309** [comment]
Thanks!
